version: '3.7'

services:
  ur-shortener-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ur-shortener-dev
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev
  redis:
    image: "redis:alpine"
    hostname: redis
    command: --port 6800
    ports: 
      - '6800:6800'
    expose:
      - '6800'
